---
title: "Bruce Becker be blogging"
description: >
  Bruce Becker:
  ex-physicist and volleyball freak;
  automator;
  quasi socialist;
  skeptic; African;
  Islander;  dad; ðŸ ðŸš€ ðŸ¤” ðŸ‡¿ðŸ‡¦ ðŸŒ‹ ðŸ‡®ðŸ‡¹
logo: personal-logo.png
disqus_shortname: brucellino
# Assign a default image for your site's header and footer
default_bg: default-bg.jpg
share: true
# Read Time is a calculator to provide post read-time based on word count.
# Usage is recommended.
readtime: true
# Change url to your domain. Leave localhost server or blank
# when working locally.
url: https://brucellino.github.io/blog/
owner:
  name: Bruce Becker
  avatar: bruce-becker.jpg
  email: brucellino@gmail.com
  description: >
    Bruce Becker: ex-physicist and volleyball freak;
    quasi socialist;
    doubledad;
    not-quite-hacker;
    grid guy;
    open everything.
  twitter: brusisceddu
  github: brucellino
  stackexchange: https://stackexchange.com/users/3206984/bruce-becker
  linkedin: brucellino
  keybase: brucellino
  flickr: brucellino

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  #  - title:                     <i class="icon-book"></i> Documentation
  #    url:                       /documentation
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: Bruce who?
    url: /about

home_links:
  - title: Home
    url: https://brucellino.github.io
    internal: false
  - title: About
    url: /about
    internal: true
  - title: Articles
    url: /articles
    internal: true
  - title: Todo
    url: /writing-list
    internal: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Africa/Johannesburg
future: true
highlighter: rouge
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
syntax_highlighter_opts:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: true
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10

include: []
exclude:
  [
    "lib",
    "config.rb",
    "Gemfile",
    "Capfile",
    "Gemfile.lock",
    "config",
    "log",
    "Rakefile",
    "Rakefile.rb",
    "tmp",
    "less",
    "*.sublime-project",
    "*.sublime-workspace",
    "test",
    "spec",
    "Gruntfile.js",
    "package.json",
    "node_modules",
  ]
